name: AssociationSchemes
version: 1.0.0
date: 2019-04-10
description: A GAP package for working with association schemes and homogeneous
coherent configurations.

authors:
    - name: Jesse Lansdown
      url: http://www.jesselansdown.com
    - name: John Bamberg
      url: http://school.maths.uwa.edu.au/~bamberg/
    - name: Akihide Hanaki
      url: http://math.shinshu-u.ac.jp/~hanaki/

maintainers:
    - name: Jesse Lansdown
      url: http://www.jesselansdown.com
    - name: John Bamberg
      url: http://school.maths.uwa.edu.au/~bamberg/

GAP: ">=4.8.1"
  
needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "NautyTracesInterface"
      version: ">= 0.2"
      url: "https://github.com/sebasguts/NautyTracesInterface"

www: http://www.jesselansdown.com/AssociationSchemes
readme: README.md
packageinfo: http://www.jesselansdown.com/AssociationSchemes/PackageInfo.g
github: https://github.com/jesselansdown/AssociationSchemes/

downloads:
    - name: .tar.gz
      url: https://github.com/jesselansdown/AssociationSchemes/archive/v1.0.0.tar.gz


abstract: AssociationSchemes is a <span class="pkgname">GAP</span> package for working with association schemes and homogeneous coherent configurations.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf

