name: AssociationSchemes
version: "2.1.0"
date: 2022-06-17
description: |
    A GAP package for working with association schemes and homogeneous coherent configurations

authors:
    - name: John Bamberg
      url: http://school.maths.uwa.edu.au/~bamberg/
    - name: Akihide Hanaki
      url: http://math.shinshu-u.ac.jp/~hanaki/
    - name: Jesse Lansdown
      url: http://www.jesselansdown.com

maintainers:
    - name: John Bamberg
      url: http://school.maths.uwa.edu.au/~bamberg/
    - name: Akihide Hanaki
      url: http://math.shinshu-u.ac.jp/~hanaki/
    - name: Jesse Lansdown
      url: http://www.jesselansdown.com

GAP: ">= 4.9"

needed-pkgs:
    - name: "GRAPE"
      version: ">=4.8.1"
      url: "https://gap-packages.github.io/grape"
    - name: "Digraphs"
      version: ">=0.13.0"
      url: "https://digraphs.github.io/Digraphs"
    - name: "cvec"
      version: ">=2.6.1"
      url: "https://gap-packages.github.io/cvec"

suggested-pkgs:
    - name: "NautyTracesInterface"
      version: ">=0.2"
      url: "https://gap-packages.github.io/NautyTracesInterface/"

www: http://www.jesselansdown.com/AssociationSchemes
readme: README.md
packageinfo: http://www.jesselansdown.com/AssociationSchemes/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/jesselansdown/AssociationSchemes/releases/download/v2.1.0/AssociationSchemes-2.1.0.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BHL22</span>]   <b class='BibAuthor'>Bamberg, J., Hanaki, A. and Lansdown, J.</b>,
     <i class='BibTitle'>AssociationSchemes, A GAP package for working with association schemes and homogeneous coherent configurations,
             Version 2.1.0</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="http://www.jesselansdown.com/AssociationSchemes">http://www.jesselansdown.com/AssociationSchemes</a></span>.
    </p>
    

bibtex: |
    @misc{ AssociationSchemes2.1.0,
      author =           {Bamberg, J. and Hanaki, A. and Lansdown, J.},
      title =            {{AssociationSchemes},  A  GAP package for working with
                          association    schemes    and   homogeneous   coherent
                          configurations, {V}ersion 2.1.0},
      month =            {Jun},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href
                          {http://www.jesselansdown.com/AssociationSchemes}
                          {\texttt{http://www.jesselansdown.com/}\discretionary
                          {}{}{}\texttt{AssociationSchemes}}},
      printedkey =       {BHL22}
    }

